name: Build Status
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - "v*"
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: 16

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: public_npm
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: List CI env variables
        run: |
          cat /etc/lsb-release
          echo $(cmake --version)
          echo node-js $(node -v)
      - name: Setup workspace
        run: |
          npm ci
          npm run audit
          npm run setup
      - name: Build all
        run: |
          npm run compile
#      todo uncomment these before merging
#      - name: Test and collect coverage
#        run: |
#          npm run coverage
#          npm run create-coverage:lcov
#      - name: report to coveralls
#        uses: coverallsapp/github-action@master
#        with:
#          github-token: ${{ secrets.github_token }}
      - name: dry-run rc publishing
        if: success() && !(startsWith( github.ref, 'refs/tags/'))
        run: |
          echo ${NPM_TOKEN:0:7}
          npm run lerna:pack
        env:
          NPM_TOKEN: ${{SECRETS.NPM_TOKEN}}
      - name: rc publishing
        if: success() && (startsWith( github.ref, 'refs/tags/'))
        run: |
          echo ${NPM_TOKEN:0:7}
          echo "gonna publish here"
        env:
          NPM_TOKEN: ${{SECRETS.NPM_TOKEN}}
