name: Build Status
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - "v*"
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: 16

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}
      - run: cat /etc/lsb-release
      - run: echo $(cmake --version)
      - run: echo node-js $(node -v)
      - run: npm ci
      - run: npm run setup
      - run: npm run compile
      - run: npm run audit
  #       todo uncomment before merging
  #      - run: npm run coverage
  #      - run: npm run create-coverage:lcov
  #      - name: report to coveralls
  #        uses: coverallsapp/github-action@master
  #        with:
  #          github-token: ${{ secrets.github_token }}
  rc-dry-run:
    runs-on: ubuntu-latest
    environment: public_npm
    needs: [build-and-test]
    if: success() && !(startsWith( github.ref, 'refs/tags/'))
    steps:
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: Check NPM_TKN
        run: |
          echo ${NPM_TOKEN:0:7}
          npm run lerna:pack
        env:
          NPM_TOKEN: ${{SECRETS.NPM_TOKEN}}
