name: Next Status
on:
  push:
    branches: [ feature/**, release/** ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: cat /etc/lsb-release
      - run: echo $(cmake --version)
      - run: echo node-js $(node -v)
      - run: npm ci
      - run: npm run setup
      - run: npm run compile
      - run: npm run coverage