name: Next Status
on:
  workflow_dispatch:
  push:
    branches: [ feature/**, release/**, fix/** ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: cat /etc/lsb-release
      - run: echo $(cmake --version)
      - run: echo node-js $(node -v)
      - run: npm ci
      - run: npm run setup
      - run: npm run compile
      - run: npm run audit
#      - run: npm run coverage